PATCH http://localhost:3000/ HTTP/1.1
content-type: application/json

{
    "name": "MassHire Career Center",
    "webpage": "masshiredowntownboston.org",
    "phone": "(617)942-6885",
    "street": "75 Federal Street, 3rd Floor",
    "city": "Boston",
    "state": "MA",
    "zip": "02110"
}

